modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "mugi_exporter"
version = "${version}"
displayName = "MugiExporter"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.mugi_exporter]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mugi_exporter]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "mugi_exporter.mixins.json"
